-- Patients Raw Table

CREATE OR REPLACE TABLE RAW.PATIENTS_RAW (
PATIENT_ID NUMBER,
PATIENT_NAME VARCHAR,
GENDER VARCHAR,
AGE NUMBER
);

-- Doctors Raw Table

CREATE OR REPLACE TABLE RAW.DOCTORS_RAW (
DOCTOR_ID NUMBER,
DOCTOR_NAME VARCHAR,
DEPARTMENT VARCHAR,
EXPERIENCE_YEARS NUMBER
);

-- Appointments Raw Table

CREATE OR REPLACE TABLE RAW.APPOINTMENTS_RAW (
APPOINTMENT_ID NUMBER,
PATIENT_ID NUMBER,
DOCTOR_ID NUMBER,
APPOINTMENT_DATE DATE,
APPOINTMENT_STATUS VARCHAR,
BILLING_AMOUNT NUMBER,
TREATMENT_COST NUMBER
);

-- Stage

CREATE OR REPLACE STAGE RAW.HEALTHCARE_STAGE;
