-- Patient Dimension

CREATE OR REPLACE TABLE CURATED.DIM_PATIENT (
PATIENT_ID NUMBER,
PATIENT_NAME VARCHAR,
GENDER VARCHAR,
AGE NUMBER
);

-- Doctor Dimension

CREATE OR REPLACE TABLE CURATED.DIM_DOCTOR (
DOCTOR_ID NUMBER,
DOCTOR_NAME VARCHAR,
DEPARTMENT VARCHAR,
EXPERIENCE_YEARS NUMBER
);

-- Date Dimension

CREATE OR REPLACE TABLE CURATED.DIM_DATE (
DATE_ID NUMBER,
FULL_DATE DATE,
MONTH NUMBER,
QUARTER NUMBER,
YEAR NUMBER
);
