-- Fact Appointments

CREATE OR REPLACE TABLE CURATED.FACT_APPOINTMENTS (
APPOINTMENT_ID NUMBER,
PATIENT_ID NUMBER,
DOCTOR_ID NUMBER,
DATE_ID NUMBER,
APPOINTMENT_STATUS VARCHAR,
BILLING_AMOUNT NUMBER,
TREATMENT_COST NUMBER
);

-- Load Patient Dimension

INSERT INTO CURATED.DIM_PATIENT
SELECT *
FROM RAW.PATIENTS_RAW;

-- Load Doctor Dimension

INSERT INTO CURATED.DIM_DOCTOR
SELECT *
FROM RAW.DOCTORS_RAW;

-- Load Fact Table

INSERT INTO CURATED.FACT_APPOINTMENTS
SELECT
APPOINTMENT_ID,
PATIENT_ID,
DOCTOR_ID,
TO_NUMBER(TO_CHAR(APPOINTMENT_DATE,'YYYYMMDD')) AS DATE_ID,
APPOINTMENT_STATUS,
BILLING_AMOUNT,
TREATMENT_COST
FROM RAW.APPOINTMENTS_RAW;
