-- Monthly Revenue View

CREATE OR REPLACE VIEW CURATED.V_MONTHLY_REVENUE AS
SELECT
YEAR,
MONTH,
SUM(BILLING_AMOUNT) AS REVENUE
FROM CURATED.FACT_APPOINTMENTS F
JOIN CURATED.DIM_DATE D
ON F.DATE_ID =
TO_NUMBER(TO_CHAR(D.FULL_DATE,'YYYYMMDD'))
GROUP BY YEAR, MONTH;

-- Doctor Performance View

CREATE OR REPLACE VIEW CURATED.V_DOCTOR_PERFORMANCE AS
SELECT
D.DOCTOR_NAME,
COUNT(*) AS APPOINTMENTS,
SUM(F.BILLING_AMOUNT) AS REVENUE
FROM CURATED.FACT_APPOINTMENTS F
JOIN CURATED.DIM_DOCTOR D
ON F.DOCTOR_ID = D.DOCTOR_ID
GROUP BY D.DOCTOR_NAME;

-- Appointment Status View

CREATE OR REPLACE VIEW CURATED.V_APPOINTMENT_STATUS AS
SELECT
APPOINTMENT_STATUS,
COUNT(*) AS APPOINTMENT_COUNT
FROM CURATED.FACT_APPOINTMENTS
GROUP BY APPOINTMENT_STATUS;

